### ISSUE TITLE
Sprint 2 review

### ISSUE THREAD

**Issue by codepathreview** [AndroidTresLeches/AADP_AndroidClient#27]
@paragsagar @ns0714 @yangyzheng

**Comment by codepathreview** [comment]
Nice work so far on the group project. Your team has made decent progress in the last week. Hope you are proud of what you have achieved in ~5 weeks.
- Make sure that everyone is [contributing](https://github.com/AndroidTresLeches/AADP_AndroidClient/graphs/contributors) to the team equally and everyone is on the same page with the progress so far
- If you guys are working on personal branches, make sure to keep sending pull requests and keep merging code.
- Keep working on integrating the core flows and make sure all pieces fit together perfectly.
- Keep all the issues up to date to better track your progress, and please close all tasks from Sprint 1.
- Consult with your mentors to get their feedback as often as you can. Remember they are here to help!

Please remember to submit the GIF walkthrough of your functional app latest by Monday night. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Looking forward to seeing your submission this Monday!

**Comment by paragsagar** [comment]
Closing sprint 2
