### ISSUE TITLE
Error While Adding Calendar Event from Event List Page. 

### ISSUE THREAD

**Issue by paragsagar** [AndroidTresLeches/AADP_AndroidClient#56]
10-27 06:29:37.563: E/AndroidRuntime(1656): FATAL EXCEPTION: main
10-27 06:29:37.563: E/AndroidRuntime(1656): Process: com.tresleches.aadp, PID: 1656
10-27 06:29:37.563: E/AndroidRuntime(1656): java.lang.NumberFormatException: Invalid int: "10:00"
10-27 06:29:37.563: E/AndroidRuntime(1656):     at java.lang.Integer.invalidInt(Integer.java:137)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at java.lang.Integer.parse(Integer.java:374)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at java.lang.Integer.parseInt(Integer.java:365)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at java.lang.Integer.parseInt(Integer.java:331)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at com.tresleches.aadp.adapter.EventArrayAdapter$1.onClick(EventArrayAdapter.java:126)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at android.view.View.performClick(View.java:4438)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at android.view.View$PerformClick.run(View.java:18422)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at android.os.Handler.handleCallback(Handler.java:733)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at android.os.Handler.dispatchMessage(Handler.java:95)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at android.os.Looper.loop(Looper.java:136)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at android.app.ActivityThread.main(ActivityThread.java:5017)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at java.lang.reflect.Method.invokeNative(Native Method)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at java.lang.reflect.Method.invoke(Method.java:515)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
10-27 06:29:37.563: E/AndroidRuntime(1656):     at dalvik.system.NativeStart.main(Native Method)

**Comment by ns0714** [comment]
Fixed
