### ISSUE TITLE
Open location in google maps

### ISSUE THREAD

**Issue by ns0714** [AndroidTresLeches/AADP_AndroidClient#61]
Completed

**Comment by fcduarte** [comment]
I've just checked out the latest code from master, when I click on "Open in Maps" the app crashes. Here's the trace:

10-27 22:37:45.970: E/AndroidRuntime(2228): FATAL EXCEPTION: main
10-27 22:37:45.970: E/AndroidRuntime(2228): android.content.ActivityNotFoundException: Unable to find explicit activity class {com.google.android.apps.maps/com.google.android.maps.MapsActivity}; have you declared this activity in your AndroidManifest.xml?
10-27 22:37:45.970: E/AndroidRuntime(2228):     at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1628)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at android.app.Activity.startActivityForResult(Activity.java:3390)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at android.app.Activity.startActivityForResult(Activity.java:3351)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:839)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at android.app.Activity.startActivity(Activity.java:3587)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at android.app.Activity.startActivity(Activity.java:3555)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at com.tresleches.aadp.activity.EventDetailActivity$2.onClick(EventDetailActivity.java:112)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at android.view.View.performClick(View.java:4240)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at android.view.View$PerformClick.run(View.java:17721)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at android.os.Handler.handleCallback(Handler.java:730)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at android.os.Handler.dispatchMessage(Handler.java:92)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at android.os.Looper.loop(Looper.java:137)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at android.app.ActivityThread.main(ActivityThread.java:5103)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at java.lang.reflect.Method.invokeNative(Native Method)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at java.lang.reflect.Method.invoke(Method.java:525)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
10-27 22:37:45.970: E/AndroidRuntime(2228):     at dalvik.system.NativeStart.main(Native Method)

**Comment by ns0714** [comment]
@fcduarte - can u check..i just checked in the fix..added try catch if maps app is not installed.
