### ISSUE TITLE
NullPointer in EventDetailActivity (stack trace)

### ISSUE THREAD

**Issue by paragsagar** [AndroidTresLeches/AADP_AndroidClient#69]
10-28 08:05:37.111: E/AndroidRuntime(2359): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tresleches.aadp/com.tresleches.aadp.activity.EventDetailActivity}: java.lang.NullPointerException
10-28 08:05:37.111: E/AndroidRuntime(2359):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at android.app.ActivityThread.access$800(ActivityThread.java:135)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at android.os.Handler.dispatchMessage(Handler.java:102)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at android.os.Looper.loop(Looper.java:136)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at android.app.ActivityThread.main(ActivityThread.java:5017)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at java.lang.reflect.Method.invokeNative(Native Method)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at java.lang.reflect.Method.invoke(Method.java:515)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at dalvik.system.NativeStart.main(Native Method)
10-28 08:05:37.111: E/AndroidRuntime(2359): Caused by: java.lang.NullPointerException
10-28 08:05:37.111: E/AndroidRuntime(2359):     at com.tresleches.aadp.activity.EventDetailActivity$2.<init>(EventDetailActivity.java:108)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at com.tresleches.aadp.activity.EventDetailActivity.onCreate(EventDetailActivity.java:104)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at android.app.Activity.performCreate(Activity.java:5231)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
10-28 08:05:37.111: E/AndroidRuntime(2359):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
10-28 08:05:37.111: E/AndroidRuntime(2359):     ... 11 more

**Comment by paragsagar** [comment]
Main reason

10-28 08:05:37.111: E/AndroidRuntime(2359): Caused by: java.lang.NullPointerException
10-28 08:05:37.111: E/AndroidRuntime(2359): at com.tresleches.aadp.activity.EventDetailActivity$2.(EventDetailActivity.java:108)

line#108
            String destinationLatitude = Double.toString(latlng.latitude);

GPS was on

**Comment by ns0714** [comment]
fixed

**Comment by paragsagar** [comment]
closing as per neha's comments
